apiVersion: v1
kind: Pod
metadata:
  labels:
    app: demoApp
  name: tensorflow-test-pod120
spec:
  containers:
  - args:
    - echo starting; cd /tmp/; python3 train_resnet50-5e.py echo done;python3 train_resnet50-5e.py;
    command:
    - /bin/sh
    - -c
    image: nvcr.io/nvidia/tensorflow:19.10-py3
    name: tensorflow-demo-container
    ports:
    - containerPort: 80
    resources:
      limits:
        nvidia.com/gpu: 0
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
  nodeSelector:
    gpushare: 'true'
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /home/jimmy/Cats_vs_Dogs
      type: Directory
    name: test-volume
